name: Bug Report
title: '[Bug]: '
description: File a bug report
labels: [Bug]
body:
    - type: markdown
      attributes:
          value: '# Bug Report Forum'

    - type: input
      id: discord_user
      attributes:
          label: Discord Username
          description: Your discord username is required in order to include the name of the reporter when fixing a bug.
          placeholder: Ex) testuser123
      validations:
          required: true

    - type: textarea
      id: details
      attributes:
          label: Bug details
          description: Explain here clearly and concisely what the bug is and what happened. (Before submitting, please make sure you're using the latest version.)
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          description: Explain here clearly and concisely what you expect to happen.
      validations:
          required: true

    - type: textarea
      id: reproduce
      attributes:
          label: Steps to reproduce
          placeholder: |
              Ex):
              1. Go to ...
              2. Click on ...
              3.
              ...
          description: In order to properly troubleshoot, we need to reproduce the bugs you experienced.
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: References (optional)
          description: If possible, add screenshots or videos to help explain the bugs.
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional description (optional)
          description: If additional description of the bugs is needed separately, please explain it here.
      validations:
          required: false
